# Generated by Django 3.0.3 on 2020-02-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policedivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('provice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Provincialcouncils')),
            ],
        ),
        migrations.CreateModel(
            name='Provincialministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Provincialcouncils')),
            ],
        ),
        migrations.CreateModel(
            name='Provincialministrydemartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('province_ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Provincialministries')),
            ],
        ),
        migrations.CreateModel(
            name='Policestations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('police_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Policedivisions')),
            ],
        ),
    ]
