# Generated by Django 3.0.3 on 2020-03-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200302_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissions',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='code',
        ),
    ]
