# Generated by Django 3.0.3 on 2020-02-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electroaldistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('ed_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gramaniladaridivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('gdn_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_sinhala', models.CharField(max_length=250)),
                ('name_tamil', models.CharField(max_length=250)),
                ('name_english', models.CharField(max_length=250)),
                ('coordinate_east', models.FloatField()),
                ('coordinate_north', models.FloatField()),
                ('location_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('gdn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Gramaniladaridivision')),
            ],
        ),
        migrations.CreateModel(
            name='Polingdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('pd_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('electoral_district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Electroaldistrict')),
            ],
        ),
        migrations.CreateModel(
            name='Media_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('file_name', models.CharField(max_length=250)),
                ('file_type', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('loc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Location_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=20)),
                ('contact_details', models.CharField(max_length=200)),
                ('lc_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('location_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locations')),
            ],
        ),
        migrations.AddField(
            model_name='gramaniladaridivision',
            name='electoral_district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Polingdivision'),
        ),
        migrations.CreateModel(
            name='Admindistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('district_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('electoral_district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Electroaldistrict')),
            ],
        ),
    ]
