# Generated by Django 3.0.3 on 2020-02-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electroaldistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('ed_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gramaniladaridivision',
            fields=[
                ('gnd_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('gdn_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_sinhala', models.CharField(max_length=250)),
                ('name_tamil', models.CharField(max_length=250)),
                ('name_english', models.CharField(max_length=250)),
                ('coordinate_east', models.FloatField()),
                ('coordinate_north', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitute', models.FloatField()),
                ('location_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('gdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Gramaniladaridivision')),
            ],
        ),
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincialcouncils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polingdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('pd_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('electoral_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Electroaldistrict')),
            ],
        ),
        migrations.CreateModel(
            name='Media_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('media', models.FileField(upload_to='')),
                ('file_type', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Location_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=20)),
                ('contact_details', models.CharField(max_length=200)),
                ('lc_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('electoral_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Electroaldistrict')),
            ],
        ),
        migrations.AddField(
            model_name='gramaniladaridivision',
            name='polingdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Polingdivision'),
        ),
        migrations.AddField(
            model_name='electroaldistrict',
            name='provice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Provincialcouncils'),
        ),
        migrations.CreateModel(
            name='Divisionalsecretariats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('admin_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Ministries')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Ministries')),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Admindistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sinhala', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('district_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('electoral_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Electroaldistrict')),
            ],
        ),
    ]
