# Generated by Django 3.0.3 on 2020-02-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gramaniladaridivision',
            old_name='electoral_district_id',
            new_name='polingdivision_id',
        ),
    ]
