# Generated by Django 3.0.3 on 2020-02-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200217_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramaniladaridivision',
            name='gnd_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
