# Generated by Django 3.0.3 on 2020-03-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200303_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_sinhala', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(max_length=200)),
                ('name_english', models.CharField(max_length=200)),
                ('institute_type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('mother_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='location.Institutes')),
            ],
        ),
    ]
