# Generated by Django 3.0.3 on 2020-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_gramaniladaridivision_gnd_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_items',
            name='file_name',
        ),
        migrations.AddField(
            model_name='media_items',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media_items',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media_items',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
