# Generated by Django 3.0.3 on 2020-02-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20200219_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramaniladaridivision',
            name='gn_id',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
